#' Visualisation interface for the FishErIes Size and functional TYpe model.
#'
#' Launch a Shiny application, which provides a user-friendly interactive and visualisation interface for the FEISTY model. Four FEISTY setups can be simulated.
#' There are three tabs displaying basic results, food web plots, and diet plots. Please see Details below.
#'
#' @details Four FEISTY setups are \code{\link{setupBasic}}, \code{\link{setupBasic2}}, \code{\link{setupVertical}}, \code{\link{setupVertical2}} in Feisty_setup.R. 
#' The details of these setups can be found in \code{\link{setupFeisty}}.
#' Users can customize their FEISTY setups through changing the widgets on the left part of the Shiny interface and got the visualized results.
#'
#' Tab 'Rates' is generated by \code{\link{plotSimulation}} in Feisty_plotting.R, which mainly includes \code{\link{plotSSBtime}}, \code{\link{plotSpectra}}, and \code{\link{plotRates}}.
#'
#' Tab 'Network' shows food web results based on the averaged data of last 40\% simulation time. See \code{\link{plotNetwork}} in Feisty_plotting.R.
#'
#' Tab 'Diet' shows fish diet results based on the averaged data of last 40\% simulation time. See \code{\link{plotDiet}} in Feisty_plotting.R.
#'
#' @author Karline Soetaert, Ken H Andersen, Yixin Zhao
#'
#' @usage
#' webFeisty(...)
#'
#' @param ... No arguments are required for this shiny application. See Examples below.
#'
#' @return This Shiny application does not return values.
#'
#' @examples
#' webFeisty()
#'
#' @seealso 
#' \code{\link{setupBasic}},
#' \code{\link{setupBasic2}},
#' \code{\link{setupVertical}},
#' \code{\link{setupVertical2}}
#' ...
#' @aliases webFeisty
#' 
#' @export
#' 


## ====================================================================
## Call to shiny web interface
## ====================================================================

webFeisty <- function(...)
 runApp(system.file('webfeisty', package = 'FeistyR'))
